BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

CREATE TABLE users(
      id SERIAL NOT NULL,
      username VARCHAR (255) NOT NULL,
      hashed_password VARCHAR (255) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),

      UNIQUE(username),
      PRIMARY KEY (id)
);

END TRANSACTION;